version: '3'
services:
  # ウェブサーバ
  compose_webserver:
    build: ./app_dockerfile
    command: /bin/bash
    networks:
      - db_app
  # データベースサーバ
  compose_dbserver:
    build: ./db_dockerfile
    environment:
      POSTGRES_PASSWORD: postgresql
    expose:
      - '5432'
    networks:
      - db_app

networks:
  db_app:
